tinyMCE.addI18n('uk.advimage_dlg',{
tab_general:"Загальне",
tab_appearance:"Вигляд",
tab_advanced:"Додатково",
general:"Загальне",
title:"Заголовок",
preview:"Попередній перегляд",
constrain_proportions:"Зберігати пропорції",
langdir:"Напрямок письма",
langcode:"Код мови",
long_desc:"Long description link",
style:"Стиль",
classes:"Класи",
ltr:"Зліва направо",
rtl:"Зправа наліво",
id:"Атрибут Id",
map:"Атрибут map",
swap_image:"Swap image",
alt_image:"Альтернативне зображення",
mouseover:"при навеленні миші",
mouseout:"при відведенні миші",
misc:"Різне",
example_img:"Попередній перегляд",
missing_alt:"Ви певні, що бажаєте продовжити, не заповнюючи опис зображення? Без зображення буде недоступне користувачам з деякими вадами, а також користувачам текстових браузерів та тим, хто вимкнув зображення.",
dialog_title:"Вставити/редагувати зображення",
src:"URL зображення",
alt:"Атрибут Alt (відображається, якщо зображення не завантажене)",
list:"Image list",
border:"Рамка",
dimensions:"Розміри",
vspace:"Вертикальний відступ",
hspace:"Горизонтальний відступ",
align:"Вирівнювання",
align_baseline:"Baseline",
align_top:"Top",
align_middle:"Middle",
align_bottom:"Bottom",
align_texttop:"Text top",
align_textbottom:"Text bottom",
align_left:"По лівому краю",
align_right:"По правому краю",
image_list:"Image list"
});