tinyMCE.addI18n('uk.advanced',{
style_select:"Стилі",
font_size:"Розмір шрифту",
fontdefault:"Шрифт",
block:"Форматувати",
paragraph:"Параграф (p)",
div:"Div",
address:"Адресa",
pre:"Преформатований (pre)",
h1:"Заголовок 1",
h2:"Заголовок 2",
h3:"Заголовок 3",
h4:"Заголовок 4",
h5:"Заголовок 5",
h6:"Заголовок 6",
blockquote:"Цитування (blockquote)",
code:"Програмний текст (code)",
samp:"Зразок коду (samp)",
dt:"Термін (dt)",
dd:"Опис терміну (dd)",
bold_desc:"Жирний (Ctrl+B)",
italic_desc:"Курсив (Ctrl+I)",
underline_desc:"Підкреслений (Ctrl+U)",
striketrough_desc:"Закреслений",
justifyleft_desc:"По лівому крію",
justifycenter_desc:"По центру",
justifyright_desc:"По правому краю",
justifyfull_desc:"По ширині",
bullist_desc:"Невпорядкований список",
numlist_desc:"Впорядкований список",
outdent_desc:"Зменшити відступ",
indent_desc:"Збільшити відступ",
undo_desc:"Відмінити (Ctrl+Z)",
redo_desc:"Застосувати (Ctrl+Y)",
link_desc:"Вставити/редагувати посилання",
unlink_desc:"Розірвати посилання",
image_desc:"Вставити/редагувати зображення",
cleanup_desc:"Cleanup messy code",
code_desc:"Редагувати HTML",
sub_desc:"Верхній індекс",
sup_desc:"Нижній індекс",
hr_desc:"Вставити горизонтальну лінію (hr)",
removeformat_desc:"Прибрати форматування",
custom1_desc:"Вставте сюди опис",
forecolor_desc:"Оберіть колір тексту",
backcolor_desc:"Оберіть колір тла",
charmap_desc:"Вставити довільний символ",
visualaid_desc:"Перемкнути напрямні/невидимі елементи",
anchor_desc:"Вставити/редагувати якір",
cut_desc:"Вирізати",
copy_desc:"Копіювати",
paste_desc:"Вставити",
image_props_desc:"Властивості зображення",
newdocument_desc:"Новий документ",
help_desc:"Допомога",
blockquote_desc:"Цитування",
clipboard_msg:"Копіювання/Вирізання/Вставка не доступні в Mozilla та Firefox.\r\nЧи бажаєте дізнатися більше про цю проблему?",
path:"Шлях",
newdocument:"Ви впевнені, що бажаєте зтерти весь вміст?",
toolbar_focus:"Перейти до іструментів - Alt+Q, Перейти до редактора - Alt-Z, Перейти до елементів шляху - Alt-X",
more_colors:"Ще кольори"
});