tinyMCE.addI18n('гл.advanced_dlg',{
about_title:"Про TinyMCE",
about_general:"Про",
about_help:"Допомога",
about_license:"Ліцензія",
about_plugins:"Плагіни",
about_plugin:"Плагін",
about_author:"Автор",
about_version:"Версія",
about_loaded:"Завантажені плагіни",
anchor_title:"Вставити/редагувати якір",
anchor_name:"Ім'я якору",
code_title:"Редактор HTML",
code_wordwrap:"Перенос слів",
colorpicker_title:"Оберіть колір",
colorpicker_picker_tab:"Вибір кольору",
colorpicker_picker_title:"Вибір кольору",
colorpicker_palette_tab:"Палітра",
colorpicker_palette_title:"Кольори палітри",
colorpicker_named_tab:"Кольори з назвами",
colorpicker_named_title:"Кольори з назвами",
colorpicker_color:"Колір:",
colorpicker_name:"Назва:",
charmap_title:"Виберіть символ",
image_title:"Вставити/редагувати зображення",
image_src:"URL зображення",
image_alt:"Опис зображення",
image_list:"Список зображень",
image_border:"Рамка",
image_dimensions:"Розміри",
image_vspace:"Вертикальний відступ",
image_hspace:"Горизонтальний відступ",
image_align:"Вирівнювання",
image_align_baseline:"Baseline",
image_align_top:"Top",
image_align_middle:"Middle",
image_align_bottom:"Bottom",
image_align_texttop:"Text top",
image_align_textbottom:"Text-bottom",
image_align_left:"По лівому краю",
image_align_right:"По правому краю",
link_title:"Вставити/редагувати посилання",
link_url:"URL посилання",
link_target:"Атрибут Target",
link_target_same:"Відкривати послання в тому ж вікні",
link_target_blank:"Відкривати посилання в новому вікні",
link_titlefield:"Атрибут Title",
link_is_email:"URL, що ви ввели, ймовірно е поштовою адресою. Чи бажаєте додати необхідний префікс mailto: ?",
link_is_external:"URL, що ви ввели, ймовірно є посиланням на інший сайт. Чи бажаєте додати необхідний префікс http:// ?",
link_list:"Link list"
});